### ISSUE TITLE
Deploying binaries

### ISSUE THREAD

**Issue by iHiD** [exercism/automated-analysis#12]
We are prototyping everything with Ruby. For this, I expect us to deploy the whole repository to the server and then run `./bin/analyze.sh`. For compiled code, we could have a target directory that is deployed instead (which would itself contain a `bin` folder).

Csharp and Go will probably set the tone here as they will be the first two compiled analyzers we use. What do @ErikSchierboom, @tehsphinx, @bitfield and anyone else think? 

The final decisions for this rest with @ccare who's job it is to carefully police this whole thing to manage our security, sanity, and AWS bill :)

**Comment by razum2um** [comment]
@iHiD what about running a docker container mounting a volume with solution? Let the author of the tool decide what's inside :) and all the stuff about security, code trust and resource management is included. Still, not sure if anything here won't run on linux/docker.. Are C# solutions here ready for .net core?

As a side note: maybe this could be helpful for students in a sense of preconfigured environment, so we'll suggest them to run the same docker command locally

**Comment by ErikSchierboom** [comment]
> what about running a docker container mounting a volume with solution?

This would also be my preference. You would then never have issue where e.g. the binary is compiled for the wrong platform or anything like that. Also, creating Docker images is just so, well, easy nowadays :) Security-wise, I think that running in a Docker container is also safer than just running a binary, although I'm sure said binary would be run on an isolated machine of course.

I wonder what @ccare thinks about this?

**Comment by bitfield** [comment]
> What do @ErikSchierboom, @tehsphinx, @bitfield and anyone else think?

I'm not completely clear what the question is.

**Comment by ErikSchierboom** [comment]
> I'm not completely clear what the question is.

I think the question is: how should we organise things to allow us to run track-specific analyzers in a uniform way. Right @iHiD?

**Comment by iHiD** [comment]
Yes. And specifically how do we organise the repos in a standard way. I'm
less fussed about how they end up on machines (e.g. docker) for this
discussion.

**Comment by bitfield** [comment]
When you say 'organize the repos in a standard way', what do you mean? Like the Exalysis repo?

**Comment by tehsphinx** [comment]
So... if I'm getting this right (making this simple):
For Ruby you do something like:
- install Dependencies
- clone ruby analyzer repo
- `./bin/analyze.sh`

And now the question with compiled languages: Usually the compiled executable is not part of the repository. Cloning it doesn't help unless we add the compiled executable -- which in turn would only bloat the `git` repo.

My thoughts:
- Docker would be one possibility with auto-building a new image if a new version tag is set. With Go such an image could be based on `SCRATCH` only adding 1 or 2 MB to the compiled executable.
- Could we use github releases? Download the `zip`, unpack and run?
- A compile pipeline should be put in place either way -- I think.

**Comment by iHiD** [comment]
Yes. This is exactly what I'm asking really. Do we want to commit binaries/releases into Git/somewhere, or do we want to compile this repo at the deployment stage, and if we choose the later, how do we standardise this.

Naively, I'm pretty against Docker in this situation. I'm not really interested in booting and shutting down Dockers per solution, as we have too much scale, so we'd need a Docker instance for each language (~50) running simultaneously on the same machine (which is gonna need a big machine), or lots of machines. As my credit card is on the AWS account, both of these feel like uncomfortable options :) 

So I'm naively edging towards either a committed binary (git/s3/whatever), or a compile at deploy time, either of which will need standarising and planning. I have a day put aside with @ccare on Thursday to discuss all this and firm up our plan for the whole infrastructure and the Ruby deployment, and to highlight any points we need to discuss more internally. We will be discussing this issue as part of that then. So any thoughts/ideas, however rough and ready, before then would be appreciated. 

For context, I've never managed an open-source project that's compiled, so I have zero experience in this. @ccare is wiser and more knowledgeable than me in these things, but I don't think he was direct experience of this situation either. We're both (always) very open to learning from your collective wisdom :)

(cc @kytrinyx for any thoughts she has too)

**Comment by kytrinyx** [comment]
> Do we want to commit binaries/releases into Git/somewhere

I would prefer not to, as Git and binary don't play very well together (it's a way to bloat your repository very, very quickly). If we want to use the binary, we should upload that as a release, and have the deploy (or whatever) script download the release instead of cloning the repository.

**Comment by tehsphinx** [comment]
One possibility: We could auto-create releases on the github repo itself to use that as a storage:
https://developer.github.com/v3/repos/releases/.

This could be done in a build pipeline:
- Travis: https://docs.travis-ci.com/user/deployment/releases/
- Github Actions (do we have/could we get access to the beta?) Sample Action: https://github.com/JasonEtco/upload-to-release

Should be done only for version tags.

Note: by default github does provide a zip to download the source code for every version tag. Sample:
https://github.com/tehsphinx/exalysis/releases

Note: if download speed is important you might want to store the release closer to home. If we do that anyway we might as well push new builds there directly.

**Comment by ErikSchierboom** [comment]
> Naively, I'm pretty against Docker in this situation. I'm not really interested in booting and shutting down Dockers per solution.

Playing devils advocate here: did you actually benchmark if there is a major performance hit? Maybe the performance hit is not as big as you'd think (I'm no Docker performance expert though). For reference, there is a [IBM paper](https://domino.research.ibm.com/library/cyberdig.nsf/papers/0929052195DD819C85257D2300681E7B/$File/rc25482.pdf) that did some performance research, and the results look promising.

> Do we want to commit binaries/releases into Git/somewhere

I would also argue against doing this. We could use GitHub releases (as others have suggested), which is also how the [CLI](https://github.com/exercism/cli/releases) is deployed.

Some more thoughts. Not all languages allow for creating self-contained executables, many will be requiring a runtime to be installed on the machine before the code can be executed. This means that running the analyzers on a single machine would result in many different runtimes being installed on that machine, which can't be good for performance either (although we should perhaps first measure this). An alternative would be to have a machine per runtime (.NET/Java,etc.), but this also has some disadvantages. Consider the scenario where the C# (.NET runtime) analyzers need version X of the runtime, whereas F# (.NET runtime) needs version Y, which is a breaking change from X. This means that this scenario also is problematic, so following this train of thought would lead to a single machine per track.

All the above would IMHO be solved by using Docker:

- Easy to deploy
- Easy to create
- Easy to maintain
- Easy to update
- Self-contained

Using Docker, one would also have the option of using Kubernetes, which would allow for more advanced scaling scenarios that might also be beneficial.

Is there perhaps someone here with some experience running Docker images in production?

**Comment by tehsphinx** [comment]
At work we recently switched to running some services on docker (as a first step towards our own kubernetes cluster).

It is all on our own servers. We have a docker registry installed where we currently push every single build from gitlab. Restarting an already downloaded docker container is instant. Updating to a new version is mostly a matter of downloading the container (across the network) and unpacking it.

Just my 2 cents. My contact with docker is mostly from a developers point of view (building them) -- not a devops (installing docker in production, scaling, etc.). I just execute a script when I want to restart or update to a new version 🤣.

**Comment by ccare** [comment]
I see from @iHiD's comments (above) that maybe this conversation is more about organisational patterns than containers vs deployment environments. However, I'll succumb to the temptation and comment anyway:

I'm not against Docker at all, and linking this with work to pre-build 'exercism' images could be nice way of joining the dots (e.g. [exercism/exercism#4740] is the latest conversation I've seen on this topic). My preference probably will be to containerize, but to run the analyzers as single-use userland containers using `runc`. I definitely agree with the general feeling here that the full Docker tools are good, and we'd probably want to use it as part of the toolchain for creating base images. 

My main opinion all on all this is that in production things should run on isolated readonly filesystems (with a solution mount like @razum2um suggested). I want to be able to really limit the system calls and resources that solution code can invoke too.

For Ruby and other dynamic languages, re-imaging containers for ever change may not be necessary. As @ErikSchierboom and @tehsphinx point out this isn't a massive overhead, but I'm also keen to avoid massive review-overhead in PRs. A subtle change to a DockerFile (perhaps changing the base image) could wildly change the code we're running in prod, so maybe keeping the runtime setup (base image) reasonably stable would be a plus.

Keeping the actual analyzer build separate would be good. I'm being deliberately vague here because the analyzer might be a prebuilt artefact we drop on - as an overlay, or a mount - or something we build as an overlay image (that's certainly more the 'docker' way, but it takes down a direction of having build tools on the base image).

Apologies if that took us off-topic. But bringing this back on-topic.... what are the build-release processes for the C# and Go analyzers? I'm a bit of a dinosaur when it comes to my knowledge of .net, and a complete novice in the Go arena. @ErikSchierboom how are you building the C# one at the moment? I see mention of nuget in the Travis file.

**Comment by ErikSchierboom** [comment]
> My preference probably will be to containerize, but to run the analyzers as single-use userland containers using runc.

> My main opinion all on all this is that in production things should run on isolated readonly filesystems

Yes, this would be smart security-wise. The analyzers also should not need more than that.

This sounds great!

> [...] how are you building the C# one at the moment?

Well, the C# analyzer currently depends on the .NET Core SDK to be installed, but I could also create platform specific binaries that only require the .NET Core runtime to be installed. In fact, I think I'm even able to create a fully self-contained build, in which the runtime is also published next to the analyzer binaries.

Regarding NuGet (the dependency manager): that is all managed in the .NET Core SDK. So I think that for the C# analyzer, we have the following options:

- Dynamically build and run the application using `dotnet run`. This means that the source code has to be checked out. Performance is not great for the first call, but I think subsequent calls are a lot faster due to caching. This option requires the full .NET Core SDK to be installed, which includes the compiler and such.
- Pre-compile the application to its platform-independent, intermediate output as a DLL. The application can then be run using `dotnet x.dll`. There is no build overhead involved, and the DLL can run on any platform, provided that the .NET Core runtime is installed.
- Pre-compile the application to a platform-dependent binary, with the .NET Core runtimes deployed next to the binary. This requires doesn't require the .NET Core SDK nor Runtime to be installed.

These are the three basic options, so there is actually quite a lot of flexibility for C# in how we can deploy. Does the above make sense?

**Comment by tehsphinx** [comment]
The build process for Go is something along the lines of:
- spin up the official golang docker container with the newest version of Go installed
- check out the source code repository (which the CI tool does for you)
- run to get all dependencies: `go mod download` (optional. will otherwise be done in the build step. This is basically doing a checkout on all the dependency git repositories)
- run for any target system (here 64bit linux): `GOOS=linux GOARCH=amd64 go build path/to/main/folder`

There might be some steps in between depending on what the project needs.

Note: result is a single binary that has no dependencies.

**Comment by bitfield** [comment]
Just as a footnote, this is absolutely what containers were made for. I recently published a [slim volume](https://cloudnativedevopsblog.com) on the topic. But as software engineers, I'm sure we'd all be happy to bikeshed technology choices until the cows come home. It's much more important to get some code up and running and see what works and what doesn't work. At the end of the day, the person doing the work gets to choose how to do it. The rest of us are just tyre-kicking!

**Comment by SleeplessByte** [comment]
For JS/TS it's running `tsc`, preferably through package.json as that also handles dependencies (e.g. `yarn install && yarn build`). It then needs `node` to run; so no single executable. Yeah there are ways to create a single executable (like electron) but this seems ridiculous for what we're trying to achieve.

on deploy:
- checkout
- install
- build
- run

**Comment by iHiD** [comment]
Thank you all for the discussion. Closing in favour of your PRs on https://github.com/exercism/automated-mentoring-support/blob/master/docs/docker.md
