### ISSUE TITLE
How to deal with naming?

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/automated-analysis#29]
For two-fer, sometimes students like to change the parameter name (e.g. from `input` to `name`). As a mentor, I would approve both, but how should an analyzer deal with this? Should there be a pre-defined list of variable names? Should be ignore variable names?

**Comment by SleeplessByte** [comment]
I think it depends on the language -- sane variable naming is usually just a stylistic choice. I know many mentors comment on it, but really, it's usually not part of learning a language.

The CaSiNg _might_ be, as some languages have very strict rules.

In general, I would not want to enforce certain parameter names in JavaScript and TypeScript.

**Comment by tehsphinx** [comment]
Currently I don't do anything automatic on variable names and I think it would be really hard to do something about it automatically. The only thing I could think of is to have a list of allowed variable names -- as you suggest -- and if the variable is not on the list, give it to a mentor to judge.

In Go there are some rules about naming. For example underscores are not allowed. `golint` will catch that... so I don't have to. Also we don't have long names like e.g. in Java. Something could be implemented for that. Right now I don't plan to do anything other what `golint` catches anyway.

There are actually very good guidelines about naming for Go: https://dave.cheney.net/practical-go/presentations/qcon-china.html#_identifiers (it's a longer read but they are really good and applicable anywhere). I'd rather provide that link though as a random resource to have a look at than asking the student to rename a variable.

**Comment by SleeplessByte** [comment]
> In Go there are some rules about naming. For example underscores are not allowed. golint will catch that... so I don't have to. Also we don't have long names like e.g. in Java. Something could be implemented for that. Right now I don't plan to do anything other what golint catches anyway.

Yes, the same for JS and TS! I do catch names starting with `underscores`, mainly because their IDE most likely will mark it as "ignore if unused", which might bite them in the behind. So I'll comment on that, with the analyser as well.

> There are actually very good guidelines about naming for Go: ...

Off topic: thank you, as a beginner in Go I actually learned something today :heart:

**Comment by kotp** [comment]
As a mentor, I don't accept `input` because that describes the functions/methods at the program language level.  Unless the exercise is about implementing that behavior for the language, of course, and then "input" describes exactly what is needed.

**Comment by pgaspar** [comment]
I also try to at least mention variable names such as `input`, `str`, `n`, etc and ask students if they can come up with something more appropriate to the specific problem they're solving.

With some analysis of existing solutions we should be able to get a list of the most used variable names and extract some conclusions out of that. Personally I think if anything we should have a list of rejected names instead of a list of allowed names. I've found a few solutions where the student writes the variable name in their native language and I'm not sure we should reject a solution because of that 🤔.

**Comment by SleeplessByte** [comment]
I don't think we should _ever_ **reject** a solution based on a shitty variable name. We're not CodeClimate -- does it teach a student fluency in a language? 

I comment often on variable names ("x is not descriptive", "seems like y is meant to be ageOnEarth") and usually the students will change it, but never do I not approve it.

**Comment by kotp** [comment]
@SleeplessByte exactly.  I don't reject it.  I just don't accept it without comment.

**Comment by pgaspar** [comment]
Good points @SleeplessByte :+1: Maybe my wording on "rejected names" was not on point. Maybe "sub-optimal names" is more accurate - as in a list of names we know are not the best choices for the problem. I agree we shouldn't disapprove on that alone though.

**Comment by SleeplessByte** [comment]
I think this is now covered by #39

**Comment by ErikSchierboom** [comment]
Agreed.
