### ISSUE TITLE
The python way

### ISSUE THREAD

**Issue by alex-bender** [exercism/automated-analysis#3]
Hello, I would like to help with python track. Don't have much to share yet but I'm working on something what can augment the job.

**Comment by iHiD** [comment]
Great. Thank you! Do any of the @exercism/python have desire/time to get involved in this (see [blog post](https://exercism.io/blog/automated-mentoring-support-project) for context)

**Comment by cmccandless** [comment]
Desire I have. Unfortunately, I don't have much spare bandwidth at the moment. I can be available for discussions and code reviews.

**Comment by alex-bender** [comment]
I have 2 questions then:
* Is it possible to join exercism/python?
* What's our next step?

**Comment by cmccandless** [comment]
> Is it possible to join exercism/python?

I'll defer that question to @iHiD 

> What's our next step?

We'll need to start working on a proof-of-concept. @iHiD, would it be better for @alex-bender to create the proof-of-concept repository under his own user, or would you prefer to create one under the exercism org from the start and grant him and I access?

**Comment by alex-bender** [comment]
@cmccandless meanwhile you can check my project page here:
https://github.com/alex-bender/mntpy/projects/1
It's rough plan of what I'm thinking to do

**Comment by kytrinyx** [comment]
@alex-bender I'm super stoked that you're excited about working on this!

I think that the most important piece to figure out is the core AST-stuff. Looking at your project I see cards about docker container, `bat` integration, and downloading a solution—I think these are probably the least important for the proof of concept, as in the next two or three months we'll be working out how all the pieces are going to fit together with the larger Exercism ecosystem. I don't think the tool/library will have to know anything about the Exercism site or infrastructure or anything, it will just need to be called with a file path, and provide some structured output in a specific way (to be determined).

I've found that for AST-stuff having a quick feedback cycle is crucial. What this typically consists of is a very bare-bones custom AST parser that takes the source code as raw text, as well as a second wrapper-function that can take a path, read the file, and pass the source text to the core parser.

This lets me write very simple unit tests, each of which defines a code snippet directly inline in the test (no fixtures or anything) and passes it to the core library, and then asserts on whatever I'm looking for. That way I don't have to mess with real files and HTTP calls and all of that.

My workflow is usually:

1. Write the simplest unit test possible
2. Get it working any way I can
3. Add a few more tests for the cases that immediately come to mind
4. Feed a bunch of real-world examples into the parser with a simple script that loops over the files that contain the samples. The goal is to see what blows up, and use that to define new minimal test cases.

Since you've been mentoring so much on the Python track, you're in the best possible place to get started. I'd recommend picking the simplest exercise that you've mentored a lot on (probably two-fer?) and then pick out two or three sample solutions that exhibit things that you typically comment on, and then write the proof of concept to just handle that, then expand from there.

As of three or four days ago, there are some students at Cornell University who are doing some course work that involves open source, and some of them have chosen to work on the Exercism AST parsing for Python. I'll introduce you all once I figure out who is who in the Cornell group :)

How does that sound, @alex-bender?

**Comment by alex-bender** [comment]
@kytrinyx Hello Katrina!

Thanks for writing such detailed answer -- really appreciate that.
Let me elaborate a bit:

The idea of that my project was born at the beginning of the year: 1st of Jan, even before I found out that there is similar project for Go thrack. So my original intention was to help myself with doing repeatiting job -- reviewing the same solutions. I've spent a couple of weekends keeping review solutions and when I've realized that it was like almost 100 exact solutions I've thought that I need to write something to help me ("coz we are damn developers, right?").

So yeah, your comments are perfectly correct:

> Looking at your project I see cards about docker container, `bat` integration, and downloading a solution—I think these are probably the least important for the proof of concept

All these parts was needed for me to build a tool for automatically doing that routines, you know..

Then I've contacted Jeremy Walker about the automation and then he told me that you guys already working on the project, but didn't reveal much.

I've continued thinking and trying to write simple POC of python AST parser (matcher of code).

It's really great news to hear that you're working wiht Cornell University and that Mozzila have awarded Exercism -- that's amazing.

What about my tiny project:

I'm going to write something simple to cover `two_fer' example,
but what confuses me is working in two threads. What I mean is my work probably will not be needed because of work of these students from Cornell.

Anyway -- thanks for reply. Hope that we will be able come up with something great in scope of that project in particular and with exercism in general.

**Comment by petertseng** [comment]
Hey there, if I can be of help here, I can comment on

> but what confuses me is working in two threads. What I mean is my work probably will not be needed because of work of these students from Cornell.

Note that the students are focusing on the static analysis portions. If I understand correctly your project has some components that, say, a mentor might run on their own machine. For example downloading a solution, running the tests. The students will not be working on these, so you do not have to worry about stepping on each others' toes there. So the only places where there is potential coordination needed would be exercise-specific analyses.

**Comment by alex-bender** [comment]
@petertseng you are completely right, but as I've mentioned earlier -- I've started the project little bit ahead of time (I've got to know about the project after) so currently, my project is a little bit outdated or at least shifted in goals.

Anyway, I've got the main idea and definitely I'll watch further development.
Thanks all!
