### ISSUE TITLE
Analyze directory should contain same files as exercism download command

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/automated-analysis#36]
When analyzing a solution, its directory should contain the same files as the `exercism download` command.

**Comment by ErikSchierboom** [comment]
@iHiD I'm currently (again) backing down on adding C# compilation, as I think the syntactic analysis will be enough once we get the tests running first. So I'll close this.

**Comment by SleeplessByte** [comment]
Actually @ErikSchierboom  and @iHiD , 

As mentioned earlier on Slack, it would be helpful to get the `package.json` at the correct sha of the state of the exercise of the student, at time of the submission, because it will hold the current version. It's better than getting the sha directly, because we would need to keep track of an internal mapping (and therefore can not apply `semver` directly).

**Comment by iHiD** [comment]
I'm happy to get all the files or provide a config.json. Let's work this out when we do the new analyzer pass in the next few days.
